script:
  - mkdir -p download
  - wget "https://www.apkmirror.com/wp-content/uploads/2019/10/5d9b0c2ce2ab1/com.google.android.apps.maps_10.26.3-1026301040_minAPI21(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk?verify=1571761690-CjYjzB8b312LpfRZ5FqgVWD8UPeB63LLSnTNFNvr%2Fxs%3D" -P download -O googlemaps.apk
  - mv googlemaps.apk download/
deploy:
  provider: s3
  access_key_id: AKIAJOHYI4KJCE6Q7MIQ
  secret_access_key: $ACCESS_KEY
  region: us-east-1
  bucket: ieee-dataport
  upload-dir: open/15769
  local_dir: download
  skip_cleanup: true
