os: osx
matrix:
  include:
  - osx_image: xcode9.4
    addons:
      homebrew:
        update: true
        taps: zhaofeng-shu33/liblemonformula
        packages:
          - glib-static  
  - osx_image: xcode10.3 
    addons:
      homebrew:
        taps: zhaofeng-shu33/liblemonformula
        packages:
          - glib-static

