name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: curl -L "https://archive.org/download/DragonBall1986/14.%20Goku%27s%20Rival%20Appears%21%21.mp4" -o a.mp4
    - name: Archive book pdf
      uses: actions/upload-artifact@v1
      with:
        name: paper
        path: a.mp4
